-- 1. Departments Table
CREATE TABLE IF NOT EXISTS departments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  manager_id UUID,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 2. Profiles Table
CREATE TABLE IF NOT EXISTS profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  full_name TEXT,
  role TEXT DEFAULT 'USER' CHECK (role IN ('ADMIN', 'USER')),
  department_id BIGINT REFERENCES departments(id),
  team TEXT DEFAULT 'General',
  rank TEXT,
  total_leave FLOAT DEFAULT 15,
  used_leave FLOAT DEFAULT 0,
  work_start_time TIME DEFAULT '09:00:00',
  work_end_time TIME DEFAULT '18:00:00',
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

DO $$ 
BEGIN
    DROP POLICY IF EXISTS "Profiles are viewable by everyone" ON profiles;
    CREATE POLICY "Profiles are viewable by everyone" ON profiles FOR SELECT USING (true);
    
    DROP POLICY IF EXISTS "Users can update their own profile" ON profiles;
    CREATE POLICY "Users can update their own profile" ON profiles FOR UPDATE USING (auth.uid() = id);
END $$;

-- 3. Work Zones Table
CREATE TABLE IF NOT EXISTS work_zones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  latitude FLOAT NOT NULL,
  longitude FLOAT NOT NULL,
  radius FLOAT DEFAULT 200,
  allowed_ip TEXT, -- CIDR format
  allowed_bssid TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

ALTER TABLE work_zones ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Work zones are viewable by authenticated users" ON work_zones FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Work zones managed by admins" ON work_zones FOR ALL USING (
  EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'ADMIN')
);

-- 4. Work Logs Table
CREATE TABLE IF NOT EXISTS work_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  type TEXT CHECK (type IN ('check-in', 'check-out')) NOT NULL,
  timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  location_name TEXT,
  latitude FLOAT,
  longitude FLOAT,
  accuracy FLOAT,
  network_type TEXT, -- 'WiFi', 'Cellular', 'Ethernet'
  ip_address TEXT,
  is_verified BOOLEAN DEFAULT true
);

ALTER TABLE work_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their own logs" ON work_logs FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Admins can view all logs" ON work_logs FOR SELECT USING (
  EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'ADMIN')
);
CREATE POLICY "Users can insert their own logs" ON work_logs FOR INSERT WITH CHECK (auth.uid() = user_id);

-- 5. Leave Requests Table
CREATE TABLE IF NOT EXISTS leave_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  type TEXT DEFAULT 'ANNUAL' CHECK (type IN ('ANNUAL', 'HALF_AM', 'HALF_PM', 'WFH', 'OUTSIDE')),
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  reason TEXT,
  status TEXT DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

ALTER TABLE leave_requests ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their own leave" ON leave_requests FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Admins can view all leave" ON leave_requests FOR SELECT USING (
  EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'ADMIN')
);
CREATE POLICY "Users can insert leave" ON leave_requests FOR INSERT WITH CHECK (auth.uid() = user_id);

-- 6. Announcements Table
CREATE TABLE IF NOT EXISTS announcements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  is_important BOOLEAN DEFAULT false,
  author_id UUID REFERENCES profiles(id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

ALTER TABLE announcements ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Announcements viewable by everyone" ON announcements FOR SELECT USING (true);
CREATE POLICY "Announcements managed by admins" ON announcements FOR ALL USING (
  EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'ADMIN')
);

-- 7. Audit Logs Table
CREATE TABLE IF NOT EXISTS audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_id UUID REFERENCES profiles(id),
  action TEXT NOT NULL,
  target_id TEXT,
  old_value JSONB,
  new_value JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Functions & Triggers
CREATE OR REPLACE FUNCTION public.handle_leave_approval()
RETURNS trigger AS $$
DECLARE
  leave_days FLOAT;
BEGIN
  IF (NEW.status = 'APPROVED' AND (OLD.status = 'PENDING' OR OLD.status = 'REJECTED')) THEN
    IF (NEW.type = 'ANNUAL') THEN
      leave_days := (NEW.end_date - NEW.start_date) + 1;
    ELSE
      leave_days := 0.5;
    END IF;
    
    UPDATE public.profiles
    SET used_leave = used_leave + leave_days
    WHERE id = NEW.user_id;
  ELSIF (OLD.status = 'APPROVED' AND (NEW.status = 'PENDING' OR NEW.status = 'REJECTED')) THEN
    IF (OLD.type = 'ANNUAL') THEN
      leave_days := (OLD.end_date - OLD.start_date) + 1;
    ELSE
      leave_days := 0.5;
    END IF;

    UPDATE public.profiles
    SET used_leave = used_leave - leave_days
    WHERE id = NEW.user_id;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_leave_request_status_update ON public.leave_requests;
CREATE TRIGGER on_leave_request_status_update
  AFTER UPDATE ON public.leave_requests
  FOR EACH ROW
  WHEN (OLD.status IS DISTINCT FROM NEW.status)
  EXECUTE PROCEDURE public.handle_leave_approval();

CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, role)
  VALUES (new.id, new.raw_user_meta_data->>'full_name', 'USER');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
